using EditSharpGUI.Scripts.App.Commands;
using EditSharpGUI.Scripts.Input;
using System.Linq;
using System.Text;

namespace EditSharpGUI.Api.Remote;

/// <summary>Every command as a Markdown page for the docs: <c>--dump-commands=FILE</c> writes it.</summary>
public static class CommandCatalog
{
	public static string Markdown()
	{
		StringBuilder page = new();
		page.AppendLine("# Command catalogue");
		page.AppendLine();
		page.AppendLine("Every command the app knows, grouped by the part before the first dot. Run one with `command.run` over RPC,");
		page.AppendLine("`EditSharpApp.Instance.Commands.Run(...)` from C#, or its menu item or key. Generated by `--dump-commands`; don't edit by hand.");

		foreach (IGrouping<string, Command> group in Commands.All.OrderBy(c => c.Id).GroupBy(c => c.Id.Split('.')[0]))
		{
			page.AppendLine();
			page.AppendLine($"## {group.Key}");
			page.AppendLine();
			page.AppendLine("| Command | Title | Default keys | What it does |");
			page.AppendLine("|---|---|---|---|");

			foreach (Command command in group)
			{
				string keys = string.Join(", ", ShortcutMap.DefaultsFor(command.Id).Select(k => $"`{k}`"));
				string help = (command.Help ?? "").Replace("|", "\\|").Replace("\n", " ");
				page.AppendLine($"| `{command.Id}` | {command.Title} | {keys} | {help} |");
			}
		}

		return page.ToString();
	}
}
