<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <AssemblyName>Halide.GodotTests</AssemblyName>
    <RootNamespace>Halide.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../halide/Halide.csproj" />
  </ItemGroup>
</Project>
